elasticsearch:
  image: segabriel/elasticsearch:5.1.1
  environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Des.network.host=0.0.0.0"
  ports:
    - "9200:9200"
    - "9300:9300"
filebeat:
  image: segabriel/filebeat:5.1.1
  volumes:
    - /opt/filebeat/logs:/var/log
  links:
    - elasticsearch
  environment:
    ELASTICSEARCH_URL: "http://elasticsearch:9200"
kibana:
  image: segabriel/kibana:5.1.1
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  environment:
    ELASTICSEARCH_URL: "http://elasticsearch:9200"
