version: '2'
services:
  zookeeper:
    image: segabriel/zookeeper:3.4.10
    ports:
      - "2181:2181"
  kafka:
    image: segabriel/kafka:0.11.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_KAFKA_HOST}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
